### PR TITLE
added permission yml and updated docker-compose file to use it

### PR DESCRIPTION
**Pull request by jasquat**
This adds a permissions yml that can be used in the app. It will set up basic permissions for an admin and a test user. More can be added to it.

The important thing is using the email address in the permission file. We use the email address as the username in the backend database to help ensure uniqueness across open id systems.

### CODE REVIEW

**Comment by fzzylogic** [comment]
Thanks so much, really appreciate your help! tl;dr is that there's some minor thing preventing Spiff login from working when email is passed, added full details below in case it can help pin the issue down. Since it worked on your side, there may be some small detail that is missing on my end..

Not sure where it's better to put notes, if there's a better place, please mention and i'll move them there:

- Added my local IP address (192.168.0...) to settings.py/ALLOWED_HOSTS and SPIFFWORKFLOW_BACKEND_OPEN_ID_SERVER_URL, 
- adjusted 'oidc_provider_settings.py' to allow the email address through (which i had wrongly tried to block to avoid the error below under the belief that [only 'iss' and 'sub' were needed](https://openid.net/specs/openid-connect-core-1_0.html#ClaimStability))
- ran 'docker-compose up --build -d' & started Django
- verified that the new permission.yml file is indeed loaded (can see the new folder with correct file content under 'Exec' tab in Docker)
- Set Django admin user to have email of admin@example.com and removed code that blanks the email address (oidc_provider_settings.py)
- After logging in, Spiff returns:
```
{
    "error_code": "user_already_exists",
    "message": "User already exists: admin@example.com",
    "status_code": 409
}
```
- It does this with any email address, including made-up ones like foo@bar.com. What is puzzling, is that login works fine with Keycloak using the same username and email, so it may be that django-oidc-provider should be configured to return some value it's not returning or some other minor thing. Below is the error log as shown in Docker fwiw:

```
2024-01-03 11:42:19 {"level": "ERROR", "message": "ApiError: User already exists: foo@bar.com. ", "loggerName": "spiffworkflow_backend", "processName": "MainProcess", "processID": 33, "threadName": "ThreadPoolExecutor-1_1", "threadID": 140646922839744, "timestamp": "2024-01-03T02:42:19.109Z", "exc_info": "
Traceback (most recent call last):
  File \"/app/venv/lib/python3.11/site-packages/flask/app.py\", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File \"/app/venv/lib/python3.11/site-packages/flask/app.py\", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/app/venv/lib/python3.11/site-packages/connexion/decorators/decorator.py\", line 68, in wrapper
    response = function(request)
               ^^^^^^^^^^^^^^^^^
  File \"/app/venv/lib/python3.11/site-packages/connexion/decorators/uri_parsing.py\", line 149, in wrapper
    response = function(request)
               ^^^^^^^^^^^^^^^^^
  File \"/app/venv/lib/python3.11/site-packages/connexion/decorators/validation.py\", line 399, in wrapper
    return function(request)
           ^^^^^^^^^^^^^^^^^
  File \"/app/venv/lib/python3.11/site-packages/connexion/decorators/parameter.py\", line 120, in wrapper
    return function(**kwargs)
           ^^^^^^^^^^^^^^^^^^
  File \"/app/src/spiffworkflow_backend/routes/authentication_controller.py\", line 146, in login_return
    user_model = AuthorizationService.create_user_from_sign_in(user_info)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/app/src/spiffworkflow_backend/services/authorization_service.py\", line 407, in create_user_from_sign_in
    user_model = UserService().create_user(**user_attributes)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/app/src/spiffworkflow_backend/services/user_service.py\", line 74, in create_user
    raise (
spiffworkflow_backend.exceptions.api_error.ApiError: ApiError: User already exists: foo@bar.com. "}
```

Set up a Realm on Keycloak to compare against, this is the token it returns (userservice.getPreferredUsername.idObject):
```
{
    "exp": 1704252923,
    "iat": 1704252623,
    "auth_time": 1704252623,
    "jti": "4946f7c5-50ce-41dc-a003-31171b67aa09",
    "iss": "http://host.docker.internal:8080/realms/SpiffRealm",
    "aud": "SpiffWorkflow",
    "sub": "1d3d3d8d-c50b-4022-a50a-f066ca566489",
    "typ": "ID",
    "azp": "SpiffWorkflow",
    "session_state": "89808458-c624-4ae4-8e9d-98105c71c689",
    "at_hash": "IZDIFSG5B67CJhhNGwApiw",
    "acr": "1",
    "sid": "89808458-c624-4ae4-8e9d-98105c71c689",
    "email_verified": false,
    "preferred_username": "admin",
    "email": "admin@example.com"
}
```

Whereas django-oidc-provider returns the below. Note that if "email" is blank (for example by not populating that field in the Django user), login works, but as soon as "email" is added login fails with the message above (fwiw the tokens can conveniently be inspected or cleared in the Django Admin / Open ID Connect Provider / Tokens / ID Token):
```
{
    "iss": "http://192.168.0.19:8010/openid",
    "sub": "admin",
    "aud": "445155",
    "exp": 1704256371,
    "iat": 1704255771,
    "auth_time": 1704254964,
    "at_hash": "pi7BA44vrJODMc3k0jXsdw",
    "nickname": "admin",
    "preferred_username": "admin",
    "email": "admin@example.com"
}
```

Please say if you have any ideas, i'm stumped ^_^.

**Comment by jasquat** [comment]
@fzzylogic it's most likely because that user already exists in the db for that particular openid server. The django server would be an open id server and keycloak would be another. When you add an email address, the system sees the user as a different username and tries to add it as a user again and gets this error. There may be a better way to handle it.

If you add a brand new user - both to the open id server and to the yml in one of the groups - does that work? You could also try removing the docker volume for the db.

**Comment by fzzylogic** [comment]
@jasquat Hooray, it works, thank you so much! Joy beyond words, this has been driving me batty ^_^. 

If i understand correctly, what this means practically is that for now 1) Django users must have email addresses in order to be granted specific Spiff perms and 2) if a Django user email address needs to be updated, currently on the Spiff side one would need to get into its internal DB and remove the user to avoid the duplicate user error. 

Above is based on: 
- Created an email-less user in permissions.yml and logged in, 
- added an email address on the Django side after the fact and verified that it fails as expected, 
- attempted to delete the user on the Spiff side using the 'site-administration' model (just a guess, haven't understood what that updates yet ^^)
- removed the user from permissions.yml and rebuilt
- finally, looked inside the container and found the db.sqlite3 file, removed the user from tables there, put the db back, then it was possible to log in with that user. Not the right way, but satisfying to verify that it worked as expected ^^.

**Comment by burnettk** [comment]
thanks, @fzzylogic , it's been nice working with you. :)

**Pull request merged**
